export const en = {
  "OBJ_1": {
    "k_a": "value_a",
    "k_b": "value_b",
  },
}

export const fr = {
  "OBJ_1": {
    "k_a": "value_a",
  },
}

export const en_complete = {
  "CROP_FINDER": {
    "CROP_FINDER": "Crop Finder",
    "DESC": "This tool for Travian Kingdoms lets you find villages with a lot of cereal field.",
    "EXPLANATION_15c_9c": "15c and 9c stands for villages with 15 and 9 cereal fields.",
    "EXPLANATION_BONUS": "The 'bonus' is the maximum bonus for crop production achievable with the surrounding oases.",
    "EXPLANATION_NATAR_VILLAGES": "NB: A natar village is considered as a free village.",
    "ON": "On",
    "OR_FROM": "or from",
    "BOTH": "both",
    "ONLY_FREE_ONES": "Only those who are free",
    "SEARCH": "search",
    "DISTANCE": "Distance",
    "COORDINATES": "Coordinates",
    "TYPE": "Type",
    "BONUS": "Bonus",
    "FREE": "Free",
    "ACTION": "Action"
  },
  "FARM_FINDER": {
    "FARM_FINDER": "Farm Finder",
    "ON": "On",
    "SETTINGS": "Settings",
    "COORDINATES": "Coordinates",
    "OR_FROM": "or from",
    "VILLAGES_POPULATION": "Villages' population",
    "PLAYERS_POPULATION": "Players' population",
    "PLAYERS_VILLAGES": "Players' villages",
    "EVOLUTION": "Evolution",
    "DAYS": "days",
    "ADDITIONAL_SETTINGS": "Additional settings",
    "ALLOW_ROMANS": "Allow Romans",
    "ALLOW_GAULS": "Allow Gauls",
    "ALLOW_TEUTONS": "Allow Teutons",
    "ALLOW_CAPITALS": "Allow capitals",
    "SEARCH_ONLY_NEW": "Search only for new farms",
    "SEARCH": "search",
    "DISTANCE": "Distance",
    "POPULATION": "Population",
    "VILLAGE": "Village",
    "PLAYER": "Player",
    "TRIBE": "Tribe",
    "VILLAGES": "Villages",
    "KINGDOM": "Kingdom",
    "ACTION": "Action",
    "OVER": "over",
    "MIN": "min",
    "MAX": "max"
  },
  "HOME": {
    "WELCOME": "Welcome to one of the most advanced Travian Kingdoms set of tools!",
    "FARM_FINDER": "Farm Finder / Innactive Finder",
    "FARM_FINDER_DESC": "Finding inactive players around you cannot be easier.",
    "CROP_FINDER": "Crop Finder",
    "CROP_FINDER_DESC": "With the crop finder it's gonna be easy to find 15c and 9c villages.",
    "TREASURE_FINDER": "Treasure Finder",
    "TREASURE_FINDER_DESC": "Looking for treasures? You have come to the right place!",
    "PLAYER_EVOLUTION": "Player Evolution",
    "PLAYER_EVOLUTION_DESC": "Track the evolution of players with beautiful charts!",
    "VILLAGE_EVOLUTION": "Village Evolution",
    "VILLAGE_EVOLUTION_DESC": "Track the evolution of villages with beautiful charts!",
    "SMITHY_CALCULATOR": "Smithy Calculator",
    "SMITHY_CALCULATOR_DESC": "Ever wonder if it was worth upgrading your units? The Smithy Calculator has the answer.",
    "ROBBER_CALCULATOR": "Robber Calculator",
    "ROBBER_CALCULATOR_DESC": "This calculator allows you to find easily how many resources you can steal from a spy report and how many units you need to steal them.",
    "TROOPS_STATS": "Troops Statistics",
    "TROOPS_STATS_DESC": "With those advanced troops statistics, you'll be able to decide which unit build and at the right time.",
    "REMINDERS": "Reminders",
    "REMINDERS_DESC": "Never miss a coordinated attack or a construction to maintain your place at the top of the classement!",
    "HIDDEN_FEATURE": "Hidden Feature",
    "HIDDEN_FEATURE_DESC_1": "Save a lot of time!",
    "HIDDEN_FEATURE_DESC_2": "Mark villages that are in your Travian farm-list. And search only for new inactive players using the Farm Finder.",
    "HIDDEN_FEATURE_DESC_3": "Sign in to access this feature."
  },
  "KINGDOM": {
    "KINGDOM": "Kingdom",
    "ON": "On",
    "KINGDOM_NOT_FOUND": "This kingdom does not exist on this server. Make sure the right server is selected.",
    "VICTORY_POINTS": "Victory points",
    "PLAYERS": "Players",
    "SHOW": "show",
    "HIDE": "hide",
    "HISTORY": "history",
    "NOTHING_TO_SHOW": "Nothing to show.",
    "DATE": "date",
    "NAME": "name",
    "POPULATION": "population",
    "EVOLUTION": "evolution",
    "VILLAGES": "villages",
    "TREASURES": "treasures",
    "ACTION": "action",
    "JOINED_KINGDOM": "joined the kingdom",
    "LEFT_KINGDOM": "left the kingdom",
    "LEFT_THE_KINGDOM_TO_JOIN": "left the kingdom to join",
    "TO_JOIN_THE_KINGDOM": "to join the kingdom",
  },
  "NEWS": {
    "NEWS": "News",
    "CLOSE": "close"
  },
  "PLAYER": {
    "PLAYER": "Player",
    "ON": "On",
    "PLAYER_NOT_FOUND": "This player does not exist on this server. Make sure the right server is selected.",
    "TRIBE": "Tribe",
    "ROLE": "Role",
    "KINGDOM": "Kingdom",
    "VILLAGES": "Villages",
    "POPULATION": "Population",
    "SHOW": "show",
    "HIDE": "hide",
    "HISTORY": "history",
    "NOTHING_TO_SHOW": "Nothing to show.",
    "DATE": "date",
    "JOINED_KINGDOM": "Joined the kingdom",
    "LEFT_KINGDOM": "Left the kingdom",
    "TO_JOIN_KINGDOM": "to join the kingdom",
    "COORDINATES": "coordinates",
    "NAME": "name",
    "7_DAYS": "7 days",
    "ACTION": "action"
  },
  "SIDENAV": {
    "HOME": "Home",
    "NEWS": "News",
    "SEARCH": "Search",
    "INACTIVE_FINDER": "Inactive Finder",
    "CROP_FINDER": "Crop Finder",
    "TREASURE_FINDER": "Treasure Finder",
    "CALCULATORS": "Calculators",
    "TROOPS_STATS": "Troop Stats",
    "DONATE": "Donate",
    "CONTACT": "Contact",
    "SETTINGS": "Settings",
    "SIGN_IN": "Sign In",
    "PLAY": "Play"
  },
  "SEARCH": {
    "TITLE": "Search for players, villages or kingdoms",
    "SEARCH_FOR": "Search for",
    "PLAYER_OR_VILLAGE": "player or village",
    "ON": "on",
    "PLAYERS": "Players",
    "VILLAGES": "Villages",
    "KINGDOMS": "Kingdoms"
  },
  "SETTINGS": {
    "SETTINGS": "Settings",
    "FARMLIST": "Farmlist",
    "LINKED_ACCOUNTS": "Linked Accounts",
    "SIGN_OUT": "Sign out",
    "NO_LINKED_ACCOUNT": "There is no linked account.",
    "SIGN_IN": "Sign in",
    "SIGN_IN_REASON": "in order to link your account.",
    "VERSION": "Version",
    "LANGUAGE": "Language"
  },
  "SIGN_IN": {
    "SIGN_IN": "Sign In",
    "FOLLOW_INSTRUCTION": "Please follow these instructions to sign in with your access token.",
    "SELECT_SERVER": "Select your server:",
    "SETUP": "<div class=\"v-margin\">Connect to your Travian Kingdoms server.</div><div class=\"v-margin\">Go to Preferences > Settings > Avatar > External tools.</div><div class=\"v-margin\">Click on the 'Create Access' button.</div><div class=\"v-margin\">Enter the page key:</div>",
    "INSTRUCTION_CREATE_ACCESS": "Click on the 'Create Access' button.",
    "INSTRUCTION_PROVIDE_ACCESS_TOKEN": "Provide your access token in order to sign in:",
    "ACCOUNT_LINKED": "Your account is linked to this server.",
    "MANAGE_ACCOUNTS": "Manage your linked accounts in the",
    "SETTINGS": "Settings",
    "PLAYER_NOT_FOUND": "Player not found. Be sure that:",
    "SELECTED_RIGHT_SERVER": "You pasted the right access token.",
    "PASTED_RIGHT_TOKEN": "You selected the right server.",
    "ACCOUNT_OLD_ENOUGH": "Your account is at least 1 day old."
  },
  "VILLAGE": {
    "VILLAGE": "Village",
    "ON": "On",
    "VILLAGE_NOT_FOUND": "This village does not exist on this server. Make sure the right server is selected.",
    "PLAYER": "player",
    "POPULATION": "population",
    "COORDINATES": "coordinates"
  }
}

export const en_absurd = {
  "CROP_FINDER": {
    "CROP_FINDER": "Crop Finder",
    "DESC": "This tool for Travian Kingdoms lets you find villages with a lot of cereal field.",
    "EXPLANATION_15c_9c": "15c and 9c stands for villages with 15 and 9 cereal fields.",
    "EXPLANATION_BONUS": "The 'bonus' is the maximum bonus for crop production achievable with the surrounding oases.",
    "EXPLANATION_NATAR_VILLAGES": "NB: A natar village is considered as a free village.",
    "ON": "On",
    "OR_FROM": "or from",
    "BOTH": "both",
    "ONLY_FREE_ONES": "Only those who are free",
    "SEARCH": "search",
    "DISTANCE": "Distance",
    "COORDINATES": "Coordinates",
    "TYPE": "Type",
    "BONUS": "Bonus",
    "FREE": "Free",
    "ACTION": "Action"
  },
  "FARM_FINDER": {
    "FARM_FINDER": "Farm Finder",
    "ON": "On",
    "SETTINGS": "Settings",
    "COORDINATES": "Coordinates",
    "OR_FROM": "or from",
    "VILLAGES_POPULATION": "Villages' population",
    "PLAYERS_POPULATION": "Players' population",
    "PLAYERS_VILLAGES": "Players' villages",
    "EVOLUTION": "Evolution",
    "DAYS": "days",
    "ADDITIONAL_SETTINGS": "Additional settings",
    "ALLOW_ROMANS": "Allow Romans",
    "ALLOW_GAULS": "Allow Gauls",
    "ALLOW_TEUTONS": "Allow Teutons",
    "ALLOW_CAPITALS": "Allow capitals",
    "SEARCH_ONLY_NEW": "Search only for new farms",
    "SEARCH": "search",
    "DISTANCE": "Distance",
    "POPULATION": "Population",
    "VILLAGE": "Village",
    "PLAYER": "Player",
    "TRIBE": "Tribe",
    "VILLAGES": "Villages",
    "KINGDOM": "Kingdom",
    "ACTION": "Action",
    "OVER": "over",
    "MIN": "min",
    "MAX": "max"
  },
  "HOME": {
    "WELCOME": "Welcome to one of the most advanced Travian Kingdoms set of tools!",
    "FARM_FINDER": "Farm Finder / Innactive Finder",
    "FARM_FINDER_DESC": "Finding inactive players around you cannot be easier.",
    "CROP_FINDER": "Crop Finder",
    "CROP_FINDER_DESC": "With the crop finder it's gonna be easy to find 15c and 9c villages.",
    "TREASURE_FINDER": "Treasure Finder",
    "TREASURE_FINDER_DESC": "Looking for treasures? You have come to the right place!",
    "PLAYER_EVOLUTION": "Player Evolution",
    "PLAYER_EVOLUTION_DESC": "Track the evolution of players with beautiful charts!",
    "VILLAGE_EVOLUTION": "Village Evolution",
    "VILLAGE_EVOLUTION_DESC": "Track the evolution of villages with beautiful charts!",
    "SMITHY_CALCULATOR": "Smithy Calculator",
    "SMITHY_CALCULATOR_DESC": "Ever wonder if it was worth upgrading your units? The Smithy Calculator has the answer.",
    "ROBBER_CALCULATOR": "Robber Calculator",
    "ROBBER_CALCULATOR_DESC": "This calculator allows you to find easily how many resources you can steal from a spy report and how many units you need to steal them.",
    "TROOPS_STATS": "Troops Statistics",
    "TROOPS_STATS_DESC": "With those advanced troops statistics, you'll be able to decide which unit build and at the right time.",
    "REMINDERS": "Reminders",
    "REMINDERS_DESC": "Never miss a coordinated attack or a construction to maintain your place at the top of the classement!",
    "HIDDEN_FEATURE": "Hidden Feature",
    "HIDDEN_FEATURE_DESC_1": "Save a lot of time!",
    "HIDDEN_FEATURE_DESC_2": "Mark villages that are in your Travian farm-list. And search only for new inactive players using the Farm Finder.",
    "HIDDEN_FEATURE_DESC_3": "Sign in to access this feature."
  },
  "KINGDOM": {
    "KINGDOM": "Kingdom",
    "ON": "On",
    "KINGDOM_NOT_FOUND": "This kingdom does not exist on this server. Make sure the right server is selected.",
    "VICTORY_POINTS": "Victory points",
    "PLAYERS": "Players",
    "SHOW": "show",
    "HIDE": "hide",
    "HISTORY": "history",
    "NOTHING_TO_SHOW": "Nothing to show.",
    "DATE": "date",
    "NAME": "name",
    "POPULATION": "population",
    "EVOLUTION": "evolution",
    "VILLAGES": "villages",
    "TREASURES": "treasures",
    "ACTION": "action",
    "JOINED_KINGDOM": "joined the kingdom",
    "LEFT_KINGDOM": "left the kingdom",
    "LEFT_THE_KINGDOM_TO_JOIN": "left the kingdom to join",
    "TO_JOIN_THE_KINGDOM": "to join the kingdom",
  },
  "NEWS": {
    "NEWS": "News",
    "CLOSE": "close"
  },
  "PLAYER": {
    "PLAYER": "Player",
    "ON": "On",
    "PLAYER_NOT_FOUND": "This player does not exist on this server. Make sure the right server is selected.",
    "TRIBE": "Tribe",
    "ROLE": "Role",
    "KINGDOM": "Kingdom",
    "VILLAGES": "Villages",
    "POPULATION": "Population",
    "SHOW": "show",
    "HIDE": "hide",
    "HISTORY": "history",
    "NOTHING_TO_SHOW": "Nothing to show.",
    "DATE": "date",
    "JOINED_KINGDOM": "Joined the kingdom",
    "LEFT_KINGDOM": "Left the kingdom",
    "TO_JOIN_KINGDOM": "to join the kingdom",
    "COORDINATES": "coordinates",
    "NAME": "name",
    "7_DAYS": "7 days",
    "ACTION": "action"
  },
  "SIDENAV": {
    "HOME": "Home",
    "NEWS": "News",
    "SEARCH": "Search",
    "INACTIVE_FINDER": "Inactive Finder",
    "CROP_FINDER": "Crop Finder",
    "TREASURE_FINDER": "Treasure Finder",
    "CALCULATORS": "Calculators",
    "TROOPS_STATS": "Troop Stats",
    "DONATE": "Donate",
    "CONTACT": "Contact",
    "SETTINGS": "Settings",
    "SIGN_IN": "Sign In",
    "PLAY": "Play"
  },
  "SEARCH": {
    "TITLE": "Search for players, villages or kingdoms",
    "SEARCH_FOR": "Search for",
    "PLAYER_OR_VILLAGE": "player or village",
    "ON": "on",
    "PLAYERS": "Players",
    "VILLAGES": "Villages",
    "KINGDOMS": "Kingdoms"
  },
  "SETTINGS": {
    "SETTINGS": "Settings",
    "FARMLIST": "Farmlist",
    "LINKED_ACCOUNTS": "Linked Accounts",
    "SIGN_OUT": "Sign out",
    "NO_LINKED_ACCOUNT": "There is no linked account.",
    "SIGN_IN": "Sign in",
    "SIGN_IN_REASON": "in order to link your account.",
    "VERSION": "Version",
    "LANGUAGE": "Language"
  },
  "SIGN_IN": {
    "SIGN_IN": "Sign In",
    "FOLLOW_INSTRUCTION": "Please follow these instructions to sign in with your access token.",
    "SELECT_SERVER": "Select your server:",
    "SETUP": "<div class=\"v-margin\">Connect to your Travian Kingdoms server.</div><div class=\"v-margin\">Go to Preferences > Settings > Avatar > External tools.</div><div class=\"v-margin\">Click on the 'Create Access' button.</div><div class=\"v-margin\">Enter the page key:</div>",
    "INSTRUCTION_CREATE_ACCESS": "Click on the 'Create Access' button.",
    "INSTRUCTION_PROVIDE_ACCESS_TOKEN": "Provide your access token in order to sign in:",
    "ACCOUNT_LINKED": "Your account is linked to this server.",
    "MANAGE_ACCOUNTS": "Manage your linked accounts in the",
    "SETTINGS": "Settings",
    "PLAYER_NOT_FOUND": "Player not found. Be sure that:",
    "SELECTED_RIGHT_SERVER": "You pasted the right access token.",
    "PASTED_RIGHT_TOKEN": "You selected the right server.",
    "ACCOUNT_OLD_ENOUGH": "Your account is at least 1 day old."
  },
  "VILLAGE": {
    "VILLAGE": "Village",
    "ON": "On",
    "VILLAGE_NOT_FOUND": "This village does not exist on this server. Make sure the right server is selected.",
    "PLAYER": "player",
    "POPULATION": "population",
    "COORDINATES": "coordinates"
  },
  "CROP_FINDER_": {
    "CROP_FINDER": "Crop Finder",
    "DESC": "This tool for Travian Kingdoms lets you find villages with a lot of cereal field.",
    "EXPLANATION_15c_9c": "15c and 9c stands for villages with 15 and 9 cereal fields.",
    "EXPLANATION_BONUS": "The 'bonus' is the maximum bonus for crop production achievable with the surrounding oases.",
    "EXPLANATION_NATAR_VILLAGES": "NB: A natar village is considered as a free village.",
    "ON": "On",
    "OR_FROM": "or from",
    "BOTH": "both",
    "ONLY_FREE_ONES": "Only those who are free",
    "SEARCH": "search",
    "DISTANCE": "Distance",
    "COORDINATES": "Coordinates",
    "TYPE": "Type",
    "BONUS": "Bonus",
    "FREE": "Free",
    "ACTION": "Action"
  },
  "FARM_FINDER_": {
    "FARM_FINDER": "Farm Finder",
    "ON": "On",
    "SETTINGS": "Settings",
    "COORDINATES": "Coordinates",
    "OR_FROM": "or from",
    "VILLAGES_POPULATION": "Villages' population",
    "PLAYERS_POPULATION": "Players' population",
    "PLAYERS_VILLAGES": "Players' villages",
    "EVOLUTION": "Evolution",
    "DAYS": "days",
    "ADDITIONAL_SETTINGS": "Additional settings",
    "ALLOW_ROMANS": "Allow Romans",
    "ALLOW_GAULS": "Allow Gauls",
    "ALLOW_TEUTONS": "Allow Teutons",
    "ALLOW_CAPITALS": "Allow capitals",
    "SEARCH_ONLY_NEW": "Search only for new farms",
    "SEARCH": "search",
    "DISTANCE": "Distance",
    "POPULATION": "Population",
    "VILLAGE": "Village",
    "PLAYER": "Player",
    "TRIBE": "Tribe",
    "VILLAGES": "Villages",
    "KINGDOM": "Kingdom",
    "ACTION": "Action",
    "OVER": "over",
    "MIN": "min",
    "MAX": "max"
  },
  "HOME_": {
    "WELCOME": "Welcome to one of the most advanced Travian Kingdoms set of tools!",
    "FARM_FINDER": "Farm Finder / Innactive Finder",
    "FARM_FINDER_DESC": "Finding inactive players around you cannot be easier.",
    "CROP_FINDER": "Crop Finder",
    "CROP_FINDER_DESC": "With the crop finder it's gonna be easy to find 15c and 9c villages.",
    "TREASURE_FINDER": "Treasure Finder",
    "TREASURE_FINDER_DESC": "Looking for treasures? You have come to the right place!",
    "PLAYER_EVOLUTION": "Player Evolution",
    "PLAYER_EVOLUTION_DESC": "Track the evolution of players with beautiful charts!",
    "VILLAGE_EVOLUTION": "Village Evolution",
    "VILLAGE_EVOLUTION_DESC": "Track the evolution of villages with beautiful charts!",
    "SMITHY_CALCULATOR": "Smithy Calculator",
    "SMITHY_CALCULATOR_DESC": "Ever wonder if it was worth upgrading your units? The Smithy Calculator has the answer.",
    "ROBBER_CALCULATOR": "Robber Calculator",
    "ROBBER_CALCULATOR_DESC": "This calculator allows you to find easily how many resources you can steal from a spy report and how many units you need to steal them.",
    "TROOPS_STATS": "Troops Statistics",
    "TROOPS_STATS_DESC": "With those advanced troops statistics, you'll be able to decide which unit build and at the right time.",
    "REMINDERS": "Reminders",
    "REMINDERS_DESC": "Never miss a coordinated attack or a construction to maintain your place at the top of the classement!",
    "HIDDEN_FEATURE": "Hidden Feature",
    "HIDDEN_FEATURE_DESC_1": "Save a lot of time!",
    "HIDDEN_FEATURE_DESC_2": "Mark villages that are in your Travian farm-list. And search only for new inactive players using the Farm Finder.",
    "HIDDEN_FEATURE_DESC_3": "Sign in to access this feature."
  },
  "KINGDOM_": {
    "KINGDOM": "Kingdom",
    "ON": "On",
    "KINGDOM_NOT_FOUND": "This kingdom does not exist on this server. Make sure the right server is selected.",
    "VICTORY_POINTS": "Victory points",
    "PLAYERS": "Players",
    "SHOW": "show",
    "HIDE": "hide",
    "HISTORY": "history",
    "NOTHING_TO_SHOW": "Nothing to show.",
    "DATE": "date",
    "NAME": "name",
    "POPULATION": "population",
    "EVOLUTION": "evolution",
    "VILLAGES": "villages",
    "TREASURES": "treasures",
    "ACTION": "action",
    "JOINED_KINGDOM": "joined the kingdom",
    "LEFT_KINGDOM": "left the kingdom",
    "LEFT_THE_KINGDOM_TO_JOIN": "left the kingdom to join",
    "TO_JOIN_THE_KINGDOM": "to join the kingdom",
  },
  "NEWS_": {
    "NEWS": "News",
    "CLOSE": "close"
  },
  "PLAYER_": {
    "PLAYER": "Player",
    "ON": "On",
    "PLAYER_NOT_FOUND": "This player does not exist on this server. Make sure the right server is selected.",
    "TRIBE": "Tribe",
    "ROLE": "Role",
    "KINGDOM": "Kingdom",
    "VILLAGES": "Villages",
    "POPULATION": "Population",
    "SHOW": "show",
    "HIDE": "hide",
    "HISTORY": "history",
    "NOTHING_TO_SHOW": "Nothing to show.",
    "DATE": "date",
    "JOINED_KINGDOM": "Joined the kingdom",
    "LEFT_KINGDOM": "Left the kingdom",
    "TO_JOIN_KINGDOM": "to join the kingdom",
    "COORDINATES": "coordinates",
    "NAME": "name",
    "7_DAYS": "7 days",
    "ACTION": "action"
  },
  "SIDENAV_": {
    "HOME": "Home",
    "NEWS": "News",
    "SEARCH": "Search",
    "INACTIVE_FINDER": "Inactive Finder",
    "CROP_FINDER": "Crop Finder",
    "TREASURE_FINDER": "Treasure Finder",
    "CALCULATORS": "Calculators",
    "TROOPS_STATS": "Troop Stats",
    "DONATE": "Donate",
    "CONTACT": "Contact",
    "SETTINGS": "Settings",
    "SIGN_IN": "Sign In",
    "PLAY": "Play"
  },
  "SEARCH_": {
    "TITLE": "Search for players, villages or kingdoms",
    "SEARCH_FOR": "Search for",
    "PLAYER_OR_VILLAGE": "player or village",
    "ON": "on",
    "PLAYERS": "Players",
    "VILLAGES": "Villages",
    "KINGDOMS": "Kingdoms"
  },
  "SETTINGS_": {
    "SETTINGS": "Settings",
    "FARMLIST": "Farmlist",
    "LINKED_ACCOUNTS": "Linked Accounts",
    "SIGN_OUT": "Sign out",
    "NO_LINKED_ACCOUNT": "There is no linked account.",
    "SIGN_IN": "Sign in",
    "SIGN_IN_REASON": "in order to link your account.",
    "VERSION": "Version",
    "LANGUAGE": "Language"
  },
  "SIGN_IN_": {
    "SIGN_IN": "Sign In",
    "FOLLOW_INSTRUCTION": "Please follow these instructions to sign in with your access token.",
    "SELECT_SERVER": "Select your server:",
    "SETUP": "<div class=\"v-margin\">Connect to your Travian Kingdoms server.</div><div class=\"v-margin\">Go to Preferences > Settings > Avatar > External tools.</div><div class=\"v-margin\">Click on the 'Create Access' button.</div><div class=\"v-margin\">Enter the page key:</div>",
    "INSTRUCTION_CREATE_ACCESS": "Click on the 'Create Access' button.",
    "INSTRUCTION_PROVIDE_ACCESS_TOKEN": "Provide your access token in order to sign in:",
    "ACCOUNT_LINKED": "Your account is linked to this server.",
    "MANAGE_ACCOUNTS": "Manage your linked accounts in the",
    "SETTINGS": "Settings",
    "PLAYER_NOT_FOUND": "Player not found. Be sure that:",
    "SELECTED_RIGHT_SERVER": "You pasted the right access token.",
    "PASTED_RIGHT_TOKEN": "You selected the right server.",
    "ACCOUNT_OLD_ENOUGH": "Your account is at least 1 day old."
  },
  "VILLAGE_": {
    "VILLAGE": "Village",
    "ON": "On",
    "VILLAGE_NOT_FOUND": "This village does not exist on this server. Make sure the right server is selected.",
    "PLAYER": "player",
    "POPULATION": "population",
    "COORDINATES": "coordinates"
  },
  "CROP_FINDER__": {
    "CROP_FINDER": "Crop Finder",
    "DESC": "This tool for Travian Kingdoms lets you find villages with a lot of cereal field.",
    "EXPLANATION_15c_9c": "15c and 9c stands for villages with 15 and 9 cereal fields.",
    "EXPLANATION_BONUS": "The 'bonus' is the maximum bonus for crop production achievable with the surrounding oases.",
    "EXPLANATION_NATAR_VILLAGES": "NB: A natar village is considered as a free village.",
    "ON": "On",
    "OR_FROM": "or from",
    "BOTH": "both",
    "ONLY_FREE_ONES": "Only those who are free",
    "SEARCH": "search",
    "DISTANCE": "Distance",
    "COORDINATES": "Coordinates",
    "TYPE": "Type",
    "BONUS": "Bonus",
    "FREE": "Free",
    "ACTION": "Action"
  },
  "FARM_FINDER__": {
    "FARM_FINDER": "Farm Finder",
    "ON": "On",
    "SETTINGS": "Settings",
    "COORDINATES": "Coordinates",
    "OR_FROM": "or from",
    "VILLAGES_POPULATION": "Villages' population",
    "PLAYERS_POPULATION": "Players' population",
    "PLAYERS_VILLAGES": "Players' villages",
    "EVOLUTION": "Evolution",
    "DAYS": "days",
    "ADDITIONAL_SETTINGS": "Additional settings",
    "ALLOW_ROMANS": "Allow Romans",
    "ALLOW_GAULS": "Allow Gauls",
    "ALLOW_TEUTONS": "Allow Teutons",
    "ALLOW_CAPITALS": "Allow capitals",
    "SEARCH_ONLY_NEW": "Search only for new farms",
    "SEARCH": "search",
    "DISTANCE": "Distance",
    "POPULATION": "Population",
    "VILLAGE": "Village",
    "PLAYER": "Player",
    "TRIBE": "Tribe",
    "VILLAGES": "Villages",
    "KINGDOM": "Kingdom",
    "ACTION": "Action",
    "OVER": "over",
    "MIN": "min",
    "MAX": "max"
  },
  "HOME__": {
    "WELCOME": "Welcome to one of the most advanced Travian Kingdoms set of tools!",
    "FARM_FINDER": "Farm Finder / Innactive Finder",
    "FARM_FINDER_DESC": "Finding inactive players around you cannot be easier.",
    "CROP_FINDER": "Crop Finder",
    "CROP_FINDER_DESC": "With the crop finder it's gonna be easy to find 15c and 9c villages.",
    "TREASURE_FINDER": "Treasure Finder",
    "TREASURE_FINDER_DESC": "Looking for treasures? You have come to the right place!",
    "PLAYER_EVOLUTION": "Player Evolution",
    "PLAYER_EVOLUTION_DESC": "Track the evolution of players with beautiful charts!",
    "VILLAGE_EVOLUTION": "Village Evolution",
    "VILLAGE_EVOLUTION_DESC": "Track the evolution of villages with beautiful charts!",
    "SMITHY_CALCULATOR": "Smithy Calculator",
    "SMITHY_CALCULATOR_DESC": "Ever wonder if it was worth upgrading your units? The Smithy Calculator has the answer.",
    "ROBBER_CALCULATOR": "Robber Calculator",
    "ROBBER_CALCULATOR_DESC": "This calculator allows you to find easily how many resources you can steal from a spy report and how many units you need to steal them.",
    "TROOPS_STATS": "Troops Statistics",
    "TROOPS_STATS_DESC": "With those advanced troops statistics, you'll be able to decide which unit build and at the right time.",
    "REMINDERS": "Reminders",
    "REMINDERS_DESC": "Never miss a coordinated attack or a construction to maintain your place at the top of the classement!",
    "HIDDEN_FEATURE": "Hidden Feature",
    "HIDDEN_FEATURE_DESC_1": "Save a lot of time!",
    "HIDDEN_FEATURE_DESC_2": "Mark villages that are in your Travian farm-list. And search only for new inactive players using the Farm Finder.",
    "HIDDEN_FEATURE_DESC_3": "Sign in to access this feature."
  },
  "KINGDOM__": {
    "KINGDOM": "Kingdom",
    "ON": "On",
    "KINGDOM_NOT_FOUND": "This kingdom does not exist on this server. Make sure the right server is selected.",
    "VICTORY_POINTS": "Victory points",
    "PLAYERS": "Players",
    "SHOW": "show",
    "HIDE": "hide",
    "HISTORY": "history",
    "NOTHING_TO_SHOW": "Nothing to show.",
    "DATE": "date",
    "NAME": "name",
    "POPULATION": "population",
    "EVOLUTION": "evolution",
    "VILLAGES": "villages",
    "TREASURES": "treasures",
    "ACTION": "action",
    "JOINED_KINGDOM": "joined the kingdom",
    "LEFT_KINGDOM": "left the kingdom",
    "LEFT_THE_KINGDOM_TO_JOIN": "left the kingdom to join",
    "TO_JOIN_THE_KINGDOM": "to join the kingdom",
  },
  "NEWS__": {
    "NEWS": "News",
    "CLOSE": "close"
  },
  "PLAYER__": {
    "PLAYER": "Player",
    "ON": "On",
    "PLAYER_NOT_FOUND": "This player does not exist on this server. Make sure the right server is selected.",
    "TRIBE": "Tribe",
    "ROLE": "Role",
    "KINGDOM": "Kingdom",
    "VILLAGES": "Villages",
    "POPULATION": "Population",
    "SHOW": "show",
    "HIDE": "hide",
    "HISTORY": "history",
    "NOTHING_TO_SHOW": "Nothing to show.",
    "DATE": "date",
    "JOINED_KINGDOM": "Joined the kingdom",
    "LEFT_KINGDOM": "Left the kingdom",
    "TO_JOIN_KINGDOM": "to join the kingdom",
    "COORDINATES": "coordinates",
    "NAME": "name",
    "7_DAYS": "7 days",
    "ACTION": "action"
  },
  "SIDENAV__": {
    "HOME": "Home",
    "NEWS": "News",
    "SEARCH": "Search",
    "INACTIVE_FINDER": "Inactive Finder",
    "CROP_FINDER": "Crop Finder",
    "TREASURE_FINDER": "Treasure Finder",
    "CALCULATORS": "Calculators",
    "TROOPS_STATS": "Troop Stats",
    "DONATE": "Donate",
    "CONTACT": "Contact",
    "SETTINGS": "Settings",
    "SIGN_IN": "Sign In",
    "PLAY": "Play"
  },
  "SEARCH__": {
    "TITLE": "Search for players, villages or kingdoms",
    "SEARCH_FOR": "Search for",
    "PLAYER_OR_VILLAGE": "player or village",
    "ON": "on",
    "PLAYERS": "Players",
    "VILLAGES": "Villages",
    "KINGDOMS": "Kingdoms"
  },
  "SETTINGS__": {
    "SETTINGS": "Settings",
    "FARMLIST": "Farmlist",
    "LINKED_ACCOUNTS": "Linked Accounts",
    "SIGN_OUT": "Sign out",
    "NO_LINKED_ACCOUNT": "There is no linked account.",
    "SIGN_IN": "Sign in",
    "SIGN_IN_REASON": "in order to link your account.",
    "VERSION": "Version",
    "LANGUAGE": "Language"
  },
  "SIGN_IN__": {
    "SIGN_IN": "Sign In",
    "FOLLOW_INSTRUCTION": "Please follow these instructions to sign in with your access token.",
    "SELECT_SERVER": "Select your server:",
    "SETUP": "<div class=\"v-margin\">Connect to your Travian Kingdoms server.</div><div class=\"v-margin\">Go to Preferences > Settings > Avatar > External tools.</div><div class=\"v-margin\">Click on the 'Create Access' button.</div><div class=\"v-margin\">Enter the page key:</div>",
    "INSTRUCTION_CREATE_ACCESS": "Click on the 'Create Access' button.",
    "INSTRUCTION_PROVIDE_ACCESS_TOKEN": "Provide your access token in order to sign in:",
    "ACCOUNT_LINKED": "Your account is linked to this server.",
    "MANAGE_ACCOUNTS": "Manage your linked accounts in the",
    "SETTINGS": "Settings",
    "PLAYER_NOT_FOUND": "Player not found. Be sure that:",
    "SELECTED_RIGHT_SERVER": "You pasted the right access token.",
    "PASTED_RIGHT_TOKEN": "You selected the right server.",
    "ACCOUNT_OLD_ENOUGH": "Your account is at least 1 day old."
  },
  "VILLAGE__": {
    "VILLAGE": "Village",
    "ON": "On",
    "VILLAGE_NOT_FOUND": "This village does not exist on this server. Make sure the right server is selected.",
    "PLAYER": "player",
    "POPULATION": "population",
    "COORDINATES": "coordinates"
  }
}